CREATE INDEX IF NOT EXISTS idx_products_category        ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand            ON products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_sku              ON products(sku) WHERE sku IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_products_active           ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_stock_levels_product      ON stock_levels(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_levels_warehouse    ON stock_levels(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product   ON stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_created   ON stock_movements(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_customer         ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_date             ON invoices(invoice_date DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_status           ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_quotations_customer       ON quotations(customer_id);
CREATE INDEX IF NOT EXISTS idx_quotations_status         ON quotations(status);
CREATE INDEX IF NOT EXISTS idx_payments_invoice          ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_date             ON payments(payment_date DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_supplier  ON purchase_orders(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_status    ON purchase_orders(status);
CREATE INDEX IF NOT EXISTS idx_delivery_status           ON delivery_orders(status);
CREATE INDEX IF NOT EXISTS idx_delivery_customer         ON delivery_orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_warranty_expiry           ON warranties(expiry_date);
CREATE INDEX IF NOT EXISTS idx_warranty_customer         ON warranties(customer_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user        ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_entity      ON activity_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created     ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user        ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_expenses_date             ON expenses(expense_date DESC);
CREATE INDEX IF NOT EXISTS idx_employees_status          ON employees(status);